<?php
//
// File generated by Dolibarr installer 3.9.1 on Jul 03, 2016
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://applicandola:8080/dolibarr';
$dolibarr_main_document_root='/home/villalbamedina/dolibarr-3.9.1-1/apps/dolibarr/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/home/villalbamedina/dolibarr-3.9.1-1/apps/dolibarr/htdocs/custom';
$dolibarr_main_data_root='/home/villalbamedina/dolibarr-3.9.1-1/apps/dolibarr/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='3308';
$dolibarr_main_db_name='bitnami_dolibarr';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='bn_dolibarr';
$dolibarr_main_db_pass='f928a5f685';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
$dolibarr_main_authentication='dolibarr';

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='6b31bfe0c6a3fc4698203fe81599ffae';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
